@startuml Worker_Registration_Screen
salt
{+
  <b>SafeHeight Monitor
  ====
  <&person> Реєстрація працівника
  ----
  {^"QR-код сканер"
    {
      [ ]
      [         Наведіть QR-код        ]
      [         на камеру пристрою     ]
      [                                ]
      [      [  QR  CODE  AREA  ]      ]
      [                                ]
    }
  }
  ----
  або
  ----
  <&key> Введіть PIN-код
  .
  {
    [      ]  [      ]  [      ]  [      ]  [      ]  [      ]
  }
  ----
  [           Увійти в систему          ]
  ----
  .
  <&info> Після успішної реєстрації:
  • Система перевірить медичний допуск
  • Активується моніторинг безпеки
  • Ви отримаєте підтвердження
}
}
@enduml
