@startuml IoT_Warning_Screen
salt
{+
  {/ 10:45 | <&signal> WiFi | <&battery> 85% }
  ====
  .
  <size:18><b><color:red>⚠ КРИТИЧНО!</color></b></size>
  ====
  .
  <size:14><b>ВИЯВЛЕНО РИЗИК ПАДІННЯ</b></size>
  .
  Ймовірність: <color:red><b>95%</b></color>
  .
  ----
  {
    <&warning> <b>Небезпечна висота</b>
    Висота: <b>12.5 метрів</b>
    .
    <&warning> <b>Нестабільне положення</b>
    Нахил: <b>45 градусів</b>
    .
    <&warning> <b>Близько до краю</b>
    Відстань: <b>0.5 метра</b>
  }
  ----
  .
  <b>РЕКОМЕНДАЦІЇ:</b>
  • Зупиніться негайно
  • Відійдіть від краю
  • Використовуйте страхувальний трос
  .
  ----
  [   <size:16><b>Я В БЕЗПЕЦІ</b></size>   ]
  .
  [ <size:14><b>ПОТРІБНА ДОПОМОГА!</b></size> ]
  ----
  .
  <&info> Інженер з охорони праці сповіщено
  <&info> Бригадир сповіщено
  .
}
}
@enduml
